version: '3.3'
services:
    nos_engine_server_standalone:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        image: nos3
        command: /usr/bin/nos_engine_server_standalone -f $SIM_BIN/nos_engine_server_config.json
        networks:
            satnet:
                aliases:
                    - nos_engine_server
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
    nos-time-driver:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        image: nos3
        command: $SIM_BIN/nos3-single-simulator time
        networks:
            satnet:
                aliases:
                    - nos_time_driver
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-simulator-terminal:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        image: nos3
        command: $SIM_BIN/nos3-single-simulator stdio-terminal
        networks:
            satnet:
                aliases:
                    - nos_terminal
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-simulator-udp-terminal:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        image: nos3
        command: $SIM_BIN/nos3-single-simulator udp-terminal
        networks:
            satnet:
                aliases:
                    - nos_udp_terminal
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-sample-simulator:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        image: nos3
        command: $SIM_BIN/nos3-sample-simulator
        networks:
            satnet:
                aliases:
                    - sample_sim
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    fsw:
        volumes:
            - '$FSW_BIN:$FSW_BIN'
        image: nos3
        command: $FSW_BIN/core-cpu1 -R PO
        networks:
            satnet:
                aliases:
                    - nos-fsw
        working_dir: $FSW_BIN
        stdin_open: true
        tty: true
        sysctls:
            - fs.mqueue.msg_max=1500
        depends_on:
            - nos_engine_server_standalone
    fortytwo:
        volumes:
            - '/opt/nos3/42/NOS3InOut:/opt/nos3/42/NOS3InOut'
            - '/tmp/.X11-unix:/tmp/.X11-unix:ro'
        image: nos3
        command: /opt/nos3/42/42 NOS3InOut
        networks:
            satnet:
                aliases:
                    - fortytwo
        working_dir: /opt/nos3/42
        tty: true
        environment:
            - DISPLAY=$DISPLAY
        depends_on:
            - nos_engine_server_standalone
    cosmos:
        volumes:
            - '$SCRIPT_DIR/../cosmos:/cosmos/cosmos'
            - '$SCRIPT_DIR/../../components/:/COMPONENTS'
            - '/tmp/.X11-unix:/tmp/.X11-unix:ro'
        image: ballaerospace/cosmos
        command: /bin/bash -c 'ruby Launcher -c nos3_launcher.txt --system nos3_system.txt && true' # true is necessary to avoid setpgrp error
        networks:
            satnet:
                aliases:
                    - cosmos
        working_dir: /cosmos/cosmos
        tty: true
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1

networks:
    satnet:


