version: '3.3'
services:
    nos_engine_server_standalone:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: /usr/bin/nos_engine_server_standalone -f $SIM_BIN/nos_engine_server_config.json
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
    nos-time-driver:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-single-simulator time
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-simulator-terminal:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-single-simulator stdio-terminal
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-simulator-udp-terminal:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-single-simulator udp-terminal
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-cam-simulator:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-cam-simulator
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-css-simulator:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-generic-css-simulator
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-eps-simulator:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-generic-eps-simulator
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-fss-simulator:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-single-simulator generic-fss-sim
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-imu-simulator:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-generic-imu-simulator
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-gps-simulator:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-gps-simulator
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-radio-simulator:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-generic-radio-simulator
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-generic-reactionwheel-simulator:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-generic-reactionwheel-simulator
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-sample-simulator:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-sample-simulator
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    nos3-torquer-simulator:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-generic-torquer-simulator
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    truth42sim:
        volumes:
            - '$SIM_DIR:$SIM_DIR'
        network_mode: host
        image: nos3
        command: $SIM_BIN/nos3-single-simulator truth42sim
        working_dir: $SIM_BIN
        stdin_open: true
        tty: true
        depends_on:
            - nos_engine_server_standalone
    fsw:
        volumes:
            - '$FSW_BIN:$FSW_BIN'
        network_mode: host
        image: nos3
        command: $FSW_BIN/core-cpu1 -R PO
        working_dir: $FSW_BIN
        stdin_open: true
        tty: true
        sysctls:
            - fs.mqueue.msg_max=1500
        depends_on:
            - nos_engine_server_standalone
    fortytwo:
        volumes:
            - '/opt/nos3/42/NOS3InOut:/opt/nos3/42/NOS3InOut'
            - '/tmp/.X11-unix:/tmp/.X11-unix:ro'
        network_mode: host
        image: nos3
        command: /opt/nos3/42/42 NOS3InOut
        working_dir: /opt/nos3/42
        tty: true
        environment:
            - DISPLAY=$DISPLAY
        depends_on:
            - nos_engine_server_standalone
    cosmos:
        volumes:
            - '$SCRIPT_DIR/../cosmos:/cosmos/cosmos'
            - '$SCRIPT_DIR/../../components/:/COMPONENTS'
            - '/tmp/.X11-unix:/tmp/.X11-unix:ro'
        network_mode: host
        image: ballaerospace/cosmos
        command: /bin/bash -c 'ruby Launcher -c nos3_launcher.txt --system nos3_system.txt && true' # true is necessary to avoid setpgrp error
        working_dir: /cosmos/cosmos
        tty: true
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
